apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-test-deployment
  namespace: dev
  labels:
    app: pipeline-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-test
  template:
    metadata:
      labels:
        app: pipeline-test
    spec:
      containers:
      - name: pipeline-test-server
        image: faridzam/pipeline-test:latest
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: pipeline-test-service
  namespace: dev
spec:
  selector:
    app: pipeline-test 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110